apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-rotator.serviceAccountName" . }}
  namespace: {{ include "cert-rotator.namespace" . }}
  labels:
    {{- include "cert-rotator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}