//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *CertRotationConfig) DeepCopyInto(out *CertRotationConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements the runtime.Object interface.
func (in *CertRotationConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this CertRotationConfig.
func (in *CertRotationConfig) DeepCopy() *CertRotationConfig {
	if in == nil {
		return nil
	}
	out := new(CertRotationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of CertRotationConfigList into another object.
func (in *CertRotationConfigList) DeepCopyInto(out *CertRotationConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertRotationConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements the runtime.Object interface.
func (in *CertRotationConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of this CertRotationConfigList.
func (in *CertRotationConfigList) DeepCopy() *CertRotationConfigList {
	if in == nil {
		return nil
	}
	out := new(CertRotationConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of CertRotationConfigSpec into another object.
func (in *CertRotationConfigSpec) DeepCopyInto(out *CertRotationConfigSpec) {
	*out = *in
	out.Notifications = in.Notifications
}

// DeepCopy returns a deep copy of this CertRotationConfigSpec.
func (in *CertRotationConfigSpec) DeepCopy() *CertRotationConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CertRotationConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of CertRotationConfigStatus into another object.
func (in *CertRotationConfigStatus) DeepCopyInto(out *CertRotationConfigStatus) {
	*out = *in
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
	if in.LastRenewedAt != nil {
		in, out := &in.LastRenewedAt, &out.LastRenewedAt
		*out = (*in).DeepCopy()
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]NodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this CertRotationConfigStatus.
func (in *CertRotationConfigStatus) DeepCopy() *CertRotationConfigStatus {
	if in == nil {
		return nil
	}
	out := new(CertRotationConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of NodeStatus into another object.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
	if in.LastRenewedAt != nil {
		in, out := &in.LastRenewedAt, &out.LastRenewedAt
		*out = (*in).DeepCopy()
	}
	if in.Certs != nil {
		in, out := &in.Certs, &out.Certs
		*out = make([]CertStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of this NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of NotificationSpec into another object.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	out.SMTP = in.SMTP
	out.Slack = in.Slack
}

// DeepCopy returns a deep copy of this NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy returns a deep copy of CertStatus.
func (in *CertStatus) DeepCopy() *CertStatus {
	if in == nil {
		return nil
	}
	out := new(CertStatus)
	*out = *in
	return out
}

// DeepCopy returns a deep copy of SMTPSpec.
func (in *SMTPSpec) DeepCopy() *SMTPSpec {
	if in == nil {
		return nil
	}
	out := new(SMTPSpec)
	*out = *in
	return out
}

// DeepCopy returns a deep copy of SlackSpec.
func (in *SlackSpec) DeepCopy() *SlackSpec {
	if in == nil {
		return nil
	}
	out := new(SlackSpec)
	*out = *in
	return out
}
